/*
 * Copyright (c) 2024 Rory Walsh
 *
 * Cabbage3 is licensed under the MIT License. See the LICENSE file for details.
 * This software is provided "as-is", without any express or implied warranty.
 * See the LICENSE file for more details.
 */

#pragma once

/* this file is generated by CabbageUtils.js */
#include <iostream>
#include <regex>
#include <string>
#include <vector>
#include "json.hpp"
#include "CabbageUtils.h"

class CabbageWidgetDescriptors
{
  public:
    // utility function to get full list of widget types contained in widgets dri
    static std::vector<std::string> getWidgetTypes()
    {
        std::vector<std::string> widgetTypes;
        std::string widgetPath = CabbageFile::getCsdPath() + "/widgets"; // Folder containing widget files

        // Check if the directory exists
        if (!std::filesystem::exists(widgetPath) || !std::filesystem::is_directory(widgetPath))
        {
            cabbage::logError << "Error: Directory " << widgetPath << " does not exist or is not a directory."
                              << std::endl;
            return widgetTypes; // Return an empty vector if directory is not found
        }

        // Iterate through the directory and extract the filenames without the extension
        for (const auto &entry : std::filesystem::directory_iterator(widgetPath))
        {
            if (entry.is_regular_file())
            {                                                            // Only process regular files
                std::string filename = entry.path().filename().string(); // Get filename
                std::string extension = entry.path().extension().string();

                // Remove extension from filename
                if (!extension.empty())
                {
                    filename = filename.substr(0, filename.length() - extension.length());
                }

                widgetTypes.push_back(filename); // Add filename to the vector
            }
        }

        return widgetTypes;
    }

    static nlohmann::json get(std::string widgetType)
    {
        std::vector<std::string> widgetTypes;
        std::string widgetPath = CabbageFile::getCsdPath() + "/widgets"; // Folder containing widget files

        if (cabbage::File::exists(widgetPath))
        {
            cabbage::logError << "Error: Directory " << widgetPath << " does not exist.";
        }

        auto jsFileContents = CabbageFile::loadJSFile(widgetPath + "/" + widgetType + ".js");
        if (!jsFileContents.empty())
        {
            return CabbageFile::extractPropsFromJS(jsFileContents);
        }

        cabAssert(false, "Invalid widget type");
    }
};
