name: cabbage3-build

on:
  push:
    branches:
      - main
      - develop

jobs:
  macos_build:
    name: macOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Debug SDK Cocoa
        run: |
          SDK_PATH=$(xcrun --show-sdk-path)
          echo "SDK path: $SDK_PATH"
          find "$SDK_PATH/System/Library/Frameworks" -maxdepth 1 -name "Cocoa.framework" || echo "Cocoa.framework not found"


      - name: Download and install CsoundLib64
        run: |
          curl -L -o csound-7.zip "https://www.dropbox.com/scl/fi/d5hnkcecizlwgvnaw1yjy/csound-7.zip?rlkey=pf9v3ucfo8hecyl5ahbacr0a0&dl=1"
          unzip csound-7.zip -d csound-7
          sudo installer -pkg csound-7/CsoundLib64-7.0-vanilla-universal.pkg -target /

      - name: Configure CMake (tests only)
        run: |
          git clone https://github.com/rorywalsh/vscabbage.git
          cd vscabbage
          git checkout develop
          cd ..

          # Get SDK path
          SDK_PATH=$(xcrun --show-sdk-path)

          cmake -GXcode -B build \
            -DCMAKE_OSX_SYSROOT=$SDK_PATH \
            -DCMAKE_OSX_DEPLOYMENT_TARGET="11.0" \
            -DCABBAGE_BUILD_TARGET=CabbageTests

      - name: Build tests
        run: cmake --build build --config Debug

      - name: Run unit tests
        run: ./build/Debug/CabbageTests --reporter compact

      - name: Clean build folder
        run: rm -rf build

      - name: Configure and build release
        run: |
          SDK_PATH=$(xcrun --show-sdk-path)
          cmake -GXcode -B build \
            -DCMAKE_OSX_SYSROOT=$SDK_PATH \
            -DCMAKE_OSX_DEPLOYMENT_TARGET="11.0" \
            -DBUILD_ALL_TARGETS=True \
            -DCMAKE_BUILD_TYPE=Release

      - name: List build directory
        run: ls -l build

      - name: Zip the macOS app bundle
        run: |
          cd build
          ls 
          zip -r CabbageBundle.zip \
            CabbagePluginSynth/CabbagePluginSynth_assets/Release/CabbagePluginSynth.vst3 \
            CabbagePluginEffect/CabbagePluginEffect_assets/Release/CabbagePluginEffect.vst3 \
            CabbagePluginSynthAUv2/CabbagePluginSynthAUv2_assets/Release/CabbagePluginSynthAUv2.component \
            CabbagePluginEffectAUv2/CabbagePluginEffectAUv2_assets/Release/CabbagePluginEffectAUv2.component \
            CabbageApp/Release/CabbageApp


      - name: Upload macOS app artifact
        uses: actions/upload-artifact@v4
        with: 
          name: CabbageBundle-macos
          path: build/CabbageBundle.zip

  windows_build:
    name: Windows build
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Download and Extract Csound
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/41g11e00yb4v66fduyw3f/Csound7.zip?rlkey=231ot83u6rmnxapwe03krm04z&st=5bzhtada&dl=1" -OutFile "Csound7.zip"
          Expand-Archive -Path "Csound7.zip" -DestinationPath "$env:ProgramFiles"
          Get-ChildItem "$env:ProgramFiles\Csound7"

      - name: Configure build
        shell: cmd
        run: |
          cmake -G "Visual Studio 17 2022" -S . -B build -DBUILD_ALL_TARGETS=ON -DCMAKE_BUILD_TYPE=Release

      - name: Zip the Windows app artifacts
        shell: pwsh
        run: |
          cd build
          Compress-Archive -Path @(
            "CabbagePluginEffect/CabbagePluginEffect_assets/VST3/Release/CabbagePluginEffect.vst3",
            "CabbagePluginSynth/CabbagePluginSynth_assets/VST3/Release/CabbagePluginSynth.vst3",
            "CabbageApp/Release/CabbageApp.exe"
          ) -DestinationPath CabbageBundle.zip

      - name: Upload Windows app artifact
        uses: actions/upload-artifact@v4
        with:
          name: CabbageBundle-windows
          path: build\CabbageBundle.zip


